name: Build and Security Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and SonarQube Scan
    runs-on: ibrahim
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  security:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      - name: npm install dependency
        run: npm install

  docker:
    name: Docker Operations
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        run: |
          docker build -t myntra .
          docker tag myntra jall1985/myntra:latest
          docker push jall1985/myntra:latest
        env:
          DOCKER_CLI_ACI: 1
      - name: Docker Scout Scan
        run: |
          docker-scout quickview jall1985/myntra:latest
          docker-scout cves jall1985/myntra:latest

  prepare_report:
    name: Prepare Report
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v2
      - name: Generate report
        run: |
          echo "Build and Security Scan Report" > report.txt
          echo "==============================" >> report.txt
          echo "Date: $(date)" >> report.txt
          # Add detailed report contents here
      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: report.txt

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: prepare_report
    steps:
      - name: Download Report
        uses: actions/download-artifact@v2
        with:
          name: security-report
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: CI Build and Security Scan Report
          body: Build and security scan completed. Report is attached.
          to: devops4577@gmail.com
          from: GitHub Actions <devops4577@gmail.com>
          secure: true
          attachment: report.txt
      - name: Send Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel-id: '#new-github-action'
          slack-message: "Build and security scan completed. Report is attached."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
