name: Build and Security Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  security:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  prepare_report:
    name: Prepare Report
    runs-on: ubuntu-latest
    needs: [build, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate report
        run: |
          echo "Build and Security Scan Report" > report.txt
          echo "==============================" >> report.txt
          echo "Date: $(date)" >> report.txt
          echo "" >> report.txt
          # Add your report contents here
          echo "Report content goes here" >> report.txt
      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: report.txt

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: prepare_report
    steps:
      - name: Download Report
        uses: actions/download-artifact@v2
        with:
          name: security-report

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: CI Build and Security Scan Report
          body: Build and security scan completed. Report is attached.
          to: devops4577@gmail.com
          from: GitHub Actions <devops4577@gmail.com>
          secure: true
          attachment: report.txt

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: '#new-github-action'
          slack-message: "Build and security scan completed. Report is attached."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

